apiVersion: apps/v1
kind: Deployment
metadata:
  name: you
spec:
  replicas: 1
  selector:
    matchLabels:
      app: you
  template:
    metadata:
      labels:
        app: you
    spec:
      containers:
      - image: okteto.dev/you:latest
        name: you
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "02120c02-f07c-4f4c-a468-cea016d321f3"
        - name: Vless_Path
          value: "/vlvdtg555"
        - name: Vmess_UUID
          value: "02120c02-f07c-4f4c-a468-cea016d321f3"
        - name: Vmess_Path
          value: "/vm6grty66"
        - name: Share_Path
          value: "/v2link"
